version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    image: 3dgen-gpu:latest
    container_name: 3dgen_gpu
    ports:
      - "8000:8000"
    env_file:
      - .env.runpod
    environment:
      - HF_HOME=/models/hf
      - TORCH_HOME=/models/torch
    volumes:
      - model_cache:/models
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    command: ["/bin/bash","-lc","/app/scripts/start.sh"]

volumes:
  model_cache:
    driver: local
